export const sampleProducts = [
  // Special Offers (Dish of the Day)
  {
    name: 'Hot & Spicy Chicken Seekh Kebab',
    description: 'Aged cheddar & truffle aioli.',
    price: 229,
    originalPrice: 299,
    discount: 23,
    category: 'Special Thali',
    type: 'special',
    image: '/images/offers/banner1.webp',
    pieces: '6 Pieces',
    time: '18 mins',
    stock: 18,
    isHot: true,
    isBestseller: true,
    rating: 4.5
  },
  {
    name: 'Butter Chicken with Naan',
    description: 'Creamy butter chicken with 2 butter naan',
    price: 279,
    originalPrice: 349,
    discount: 20,
    category: 'Deluxe Thali',
    type: 'deluxe',
    image: '/images/offers/banner2.webp',
    pieces: 'Full',
    time: '25 mins',
    stock: 12,
    isBestseller: true,
    rating: 4.8
  },
  {
    name: 'Paneer Tikka',
    description: '6 pieces of grilled paneer tikka',
    price: 199,
    originalPrice: 249,
    discount: 20,
    category: 'Classic Thali',
    type: 'classic',
    image: '/images/offers/banner3.webp',
    pieces: '6 Pieces',
    time: '20 mins',
    stock: 8,
    isHot: true,
    rating: 4.3
  },
  {
    name: 'Hyderabadi Chicken Biryani',
    description: 'Authentic Hyderabadi biryani with raita',
    price: 219,
    originalPrice: 279,
    discount: 21,
    category: 'Rice Combo',
    type: 'rice',
    image: '/images/offers/banner4.webp',
    pieces: 'Full',
    time: '30 mins',
    stock: 15,
    isHot: true,
    isBestseller: true,
    rating: 4.7
  },
  {
    name: 'Dal Makhani + 2 Tandoori Roti',
    description: 'Creamy dal makhani with tandoori roti',
    price: 149,
    originalPrice: 199,
    discount: 25,
    category: 'Comfort Thali',
    type: 'comfort',
    image: '/images/offers/banner5.webp',
    pieces: 'Combo',
    time: '15 mins',
    stock: 10,
    rating: 4.2
  },
  
  // Explore Menu Items
  {
    name: 'Wagyu Burger',
    description: 'Aged cheddar & truffle aioli.',
    price: 18.50,
    category: 'Breakfast',
    type: 'breakfast',
    image: '/images/explore-menu/burger.jpg',
    pieces: '1 Burger',
    time: '20 mins',
    stock: 15,
    isHot: true,
    rating: 4.5
  },
  {
    name: 'Truffle Pasta',
    description: 'Black truffle cream sauce.',
    price: 24.00,
    category: 'Breakfast',
    type: 'breakfast',
    image: '/images/explore-menu/white sause.avif',
    pieces: 'Full',
    time: '25 mins',
    stock: 10,
    rating: 4.8
  },
  {
    name: 'Seared Salmon',
    description: 'Lemon butter & asparagus.',
    price: 22.00,
    category: 'Healthy',
    type: 'healthy',
    image: '/images/explore-menu/delisious.avif',
    pieces: '1 Plate',
    time: '22 mins',
    stock: 8,
    isHot: true,
    rating: 4.3
  },
  {
    name: 'Sushi Crunch',
    description: 'Tuna, mayo & tempura.',
    price: 16.50,
    category: 'Breakfast',
    type: 'breakfast',
    image: '/images/explore-menu/sushi-crunch.jpg',
    pieces: '8 Pieces',
    time: '18 mins',
    stock: 12,
    rating: 4.6
  },
  {
    name: 'Classic Cheeseburger',
    description: 'Beef patty, cheddar, lettuce, tomato.',
    price: 14.50,
    category: 'Breakfast',
    type: 'breakfast',
    image: '/images/explore-menu/classic-burger.jpg',
    pieces: '1 Burger',
    time: '20 mins',
    stock: 20,
    rating: 4.2
  }
];